### PR TITLE
Setup Devise to use Twitter OAuth provider

### PR DESCRIPTION
**Pull request by jamesbrink**
@irishsox5 here are the changes to allow Devise to use the Twitter OAuth provider.

### CODE REVIEW

**Comment by irishsox5** [comment]
Hey James, I just checked out the code on my local server but I am getting  400 bad request when I try to sign in with twitter.
Neil 

```
 On Tuesday, May 19, 2015 1:57 AM, James Brink <notifications@github.com> wrote:
```

 @irishsox5 here are the changes to allow Devise to use the Twitter OAuth provider.
You can view, comment on, or merge this pull request online at:
  https://github.com/irishsox5/stakings/pull/1
Commit Summary
- fixed indentation on registrations_controller.rb
- Fixed typo in classname
- Configured Devise to use twitter oauth provider

File Changes
-  A app/controllers/callbacks_controller.rb (11) 
-  M app/controllers/registrations_controller.rb (4) 
-  M app/controllers/sessions_controller.rb (4) 
-  M app/models/user.rb (14) 
-  M config/initializers/devise.rb (55) 
-  D config/initializers/omniauth.rb (4) 
-  M config/routes.rb (18) 
-  A db/migrate/20150519054739_remove_not_null_constraing_from_users_email.rb (5) 
-  A db/migrate/20150519061616_add_unique_restraint_to_users_uid.rb (5) 
-  M db/schema.rb (17) 

Patch Links:
- https://github.com/irishsox5/stakings/pull/1.patch
- https://github.com/irishsox5/stakings/pull/1.diff

**Comment by jamesbrink** [comment]
Your local server needs to be accessible by twitter for callbacks. You can not run on localhost.

**Comment by irishsox5** [comment]
I just merged your commits. One quick question how can I enable localhost for twitter for callbacks? Or what is the best way to wok on changes in development without running into 400 bad request errors when signing in
 

```
 On Tuesday, May 19, 2015 5:35 PM, James Brink <notifications@github.com> wrote:
```

 Your local server needs to be accessible by twitter for callbacks. You can not run on localhost.—

**Comment by jamesbrink** [comment]
I think your best bet is to make your box available for the callback from twitter. open the ports from router/firewall. It's a shame they do not have a sandbox of sorts you can run locally.

**Pull request merged**
